name: Rust CI

on:
  push:
    branches: [main]
    tags:
      - 'v*'
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - name: Install protobuf compiler
        run: |
          if [[ "${{ runner.os }}" == "Linux" ]]; then
            sudo apt-get update
            sudo apt-get install -y protobuf-compiler
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            brew install protobuf
          fi
      - run: cargo fmt -- --check
      - run: cargo clippy -- -D warnings
      - run: cargo test
      - uses: cachix/cachix-action@v17
        with:
          name: darkmatter
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - uses: katyo/publish-crates@v2
        if: ${{ github.ref_type == 'tag' && !github.event.pull_request }}
        with:
          ignore-unpublished-changes: true
